# Generated by Django 5.2 on 2025-04-13 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_comment_reply'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='category',
            field=models.CharField(choices=[('Programming & Software Development', 'Programming & Software Development'), ('Networking & Cybersecurity', 'Networking & Cybersecurity'), ('Artificial Intelligence & Machine Learning', 'Artificial Intelligence & Machine Learning'), ('Data Science & Databases', 'Data Science & Databases'), ('Cloud Computing & DevOps', 'Cloud Computing & DevOps'), ('IT Fundamentals & Certifications', 'IT Fundamentals & Certifications'), ('UI/UX Design & Tools', 'UI/UX Design & Tools'), ('Game Development & AR/VR', 'Game Development & AR/VR'), ('Career & Soft Skills for IT', 'Career & Soft Skills for IT')], default=1, max_length=100),
            preserve_default=False,
        ),
    ]
