# Generated by Django 5.2 on 2025-05-03 16:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_video_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='category',
            field=models.CharField(choices=[('Programming & Software Development', 'Programming & Software Development'), ('Networking & Cybersecurity', 'Networking & Cybersecurity'), ('Artificial Intelligence & Machine Learning', 'Artificial Intelligence & Machine Learning'), ('Data Science & Databases', 'Data Science & Databases'), ('Cloud Computing & DevOps', 'Cloud Computing & DevOps'), ('IT Fundamentals & Certifications', 'IT Fundamentals & Certifications'), ('UI/UX Design & Tools', 'UI/UX Design & Tools'), ('Game Development & AR/VR', 'Game Development & AR/VR'), ('Career & Soft Skills for IT', 'Career & Soft Skills for IT')], max_length=100),
        ),
        migrations.CreateModel(
            name='ActiveSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Signed in', 'Signed in'), ('Signed out', 'Signed out')], max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SessionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_time', models.DateTimeField()),
                ('logout_time', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
