# Generated by Django 5.2 on 2025-05-03 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_remove_sessionhistory_user_usersession_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersessionhistory',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserSession',
        ),
        migrations.DeleteModel(
            name='UserSessionHistory',
        ),
    ]
