# Generated by Django 5.2 on 2025-05-15 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_remove_usersession_user_signinactivity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='embedding',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
