# Generated by Django 5.1.6 on 2025-05-19 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_profile_is_locked'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_watched_video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.video'),
        ),
    ]
